#!/usr/bin/env python3
# README.ai Writer - Because your time is worth more than documentation no one reads

import os
import sys
import datetime

# The AI part: we pretend to be smart by using templates
TEMPLATE = """# {project_name}

{description}

## Why?
Because someone told you to make a README. Now you have one.

## Installation
```bash
pip install {project_name}
```

## Usage
```python
import {project_name}

# Magic happens here (or not)
```

## Features
- It works (probably)
- Has badges (see below)
- Looks professional (from a distance)

## Badges
![Python Version](https://img.shields.io/badge/python-3.6+-blue.svg)
![License](https://img.shields.io/badge/license-MIT-green.svg)
![Downloads](https://img.shields.io/badge/downloads-0-red.svg)

## Contributing
1. Fork it
2. Fix my bugs
3. Submit PR
4. Wait forever

## License
MIT - because copying is the sincerest form of flattery

*Generated by README.ai Writer on {date} - You're welcome.*
"""

def main():
    """Main function that does the bare minimum to justify its existence"""
    
    # Get project name (default to 'my-awesome-project' because optimism)
    project_name = input("Project name (default: my-awesome-project): ") or "my-awesome-project"
    
    # Get description (users love writing these)
    description = input("Brief description: ") or "Another amazing project that will change everything (or nothing)."
    
    # Generate the masterpiece
    readme_content = TEMPLATE.format(
        project_name=project_name,
        description=description,
        date=datetime.datetime.now().strftime("%Y-%m-%d")
    )
    
    # Write to file (the actual work part)
    with open("README.md", "w") as f:
        f.write(readme_content)
    
    print(f"✓ README.md generated for '{project_name}'")
    print("⚠️  Warning: Actual project quality may vary")
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
